language: java

before_install:
  - gradle assemble
  - gradle check
  - gradle test
  - bundle install

#script:
  - gradle -Dcucumber.options="..." test
#  - bundle exec cucumber -f progress -r features /src/test/resources/gradle/cucumber/debilitarFantasmasCuandoacmanComePellets.feature
  - bundle exec cucumber /src/test/resources/gradle/cucumber/debilitarFantasmasCuandoacmanComePellets.feature
  
notifications:
  email:
    recipients:
#      - sirdemian@gmail.com
#      - sabaliauskaspablo@gmail.com
#      - salgadoema@gmail.com
#      - schabpaula@gmail.com
      - gil.maricruz@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
